MIDI - USB
MIDI kabel
USB verlengkabel
USB hub
// speakerdraad
// witte kabel 40m

3x ESP32 sender

// 4x Raspberry Pi
// 4x netwerkkabel
// 1x switch
// 1x power switch
1x Thunderbolt-ethernet

Audio-in: geluidskaartje.

Soldeerbout

8x ledbeam
// 4x
8x powerledbeam
// 4x

[!] montage tape
[!] Electric-tape
[!] Tie rips!
// [!] stekkers 16x
// [!] Verlengblokken met plek voor 8 stekkers: 4x5

UART programmer